Repository MapJiri/mapjiri-datamining, pull requests merged in 2025-02, with the labels that each got.

#2 [Feat] 대전광역시 자치구별 행정동 크롤링
  daejeon/daejeonDaedeokgu.py
  daejeon/daejeonDonggu.py
  daejeon/daejeonJunggu.py
  daejeon/daejeonSeogu.py
  daejeon/daejeonYueseonggu.py
  대전광역시_대덕구_행정동.csv
  대전광역시_동구_행정동.csv
  대전광역시_서구_행정동.csv
  대전광역시_유성구_행정동.csv
  대전광역시_중구_행정동.csv
Labels: enhancement

#5 [feat] 리뷰 데이터 크롤링
  restauants_crawler.py
  review/review.py
  test.py
  메뉴.csv
Labels: enhancement

#6 [Feat] 도커 컨테이너 이미지 Crawling 구현
  crawling/basic/Dockerfile
  crawling/basic/chrome-deps.txt
  crawling/basic/install-browser.sh
  crawling/basic/main.py
  crawling/basic/requirements.txt
Labels: enhancement

#8 chore : 대구 전체 동과 메뉴 리스트 조합하여 {대구 동, 메뉴} 형식 json 파일 생성
  crawling/formatted_keywords.json
Labels: documentation

#9 카카오맵 가게 리뷰 크롤러
  daejeon/대전광역시_대덕구_행정동.csv
  daejeon/대전광역시_동구_행정동.csv
  daejeon/대전광역시_서구_행정동.csv
  daejeon/대전광역시_유성구_행정동.csv
  daejeon/대전광역시_중구_행정동.csv
  menu/메뉴.csv
  restauants_crawler.py
  review/review.py
Labels: enhancement

#11 [Fix] 주소지 저장 로직 변경
  restauants_crawler.py
Labels: bug
